#include "LeviBloom.hpp"

#include <fstream>
#include <nlohmann/json.hpp>

LeviBloomMod &LeviBloomMod::instance() {
    static LeviBloomMod mod;
    return mod;
}

LeviBloomMod::LeviBloomMod()
    : mSelf(*ll::mod::NativeMod::current()) {}

void LeviBloomMod::loadConfig() {
    const auto dir = self().getConfigDir();
    std::filesystem::create_directories(dir);
    const auto path = dir / "config.json";

    if (!std::filesystem::exists(path)) {
        saveConfig();
        return;
    }

    try {
        std::ifstream in(path);
        nlohmann::json j;
        in >> j;
        std::scoped_lock lock(mMutex);
        mConfig.enabled = j.value("enabled", mConfig.enabled);
        mConfig.intensity = j.value("intensity", mConfig.intensity);
        mConfig.radius = j.value("radius", mConfig.radius);
        mConfig.layers = j.value("layers", mConfig.layers);
        mConfig.max_instances = j.value("max_instances", mConfig.max_instances);
        mConfig.affect_particles = j.value("affect_particles", mConfig.affect_particles);
        mConfig.affect_entities = j.value("affect_entities", mConfig.affect_entities);
        mConfig.affect_blocks = j.value("affect_blocks", mConfig.affect_blocks);
    } catch (...) {
        self().getLogger().warn("LeviBloom: invalid config.json, using defaults");
    }
}

void LeviBloomMod::saveConfig() {
    const auto dir = self().getConfigDir();
    std::filesystem::create_directories(dir);
    const auto path = dir / "config.json";

    nlohmann::json j{
        {"enabled", mConfig.enabled},
        {"intensity", mConfig.intensity},
        {"radius", mConfig.radius},
        {"layers", mConfig.layers},
        {"max_instances", mConfig.max_instances},
        {"affect_particles", mConfig.affect_particles},
        {"affect_entities", mConfig.affect_entities},
        {"affect_blocks", mConfig.affect_blocks}
    };

    std::ofstream out(path);
    out << j.dump(2) << '\n';
}

bool LeviBloomMod::load() {
    loadConfig();
    self().getLogger().info("LeviBloom NoShader {} loaded", LEVIBLOOM_VERSION);
    self().getLogger().warn(
        "LeviBloom NoShader is a renderer-integration prototype: actual halo drawing "
        "must be bound to the target Minecraft/RenderDragon build.");
    return true;
}

bool LeviBloomMod::enable() {
    self().getLogger().info(
        "LeviBloom enabled: geometry-halo mode, no GLSL/HLSL shaders generated by this module");
    return true;
}

bool LeviBloomMod::disable() {
    self().getLogger().info("LeviBloom disabled");
    return true;
}

bool LeviBloomMod::unload() {
    return true;
}
